/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseDialog: typeof import('./src/components/baseDialog/index.vue')['default']
    BlockTitle: typeof import('./src/components/blockTitle/index.vue')['default']
    FsConfigProvider: typeof import('./src/components/fsConfigProvider/index.vue')['default']
    LoadingContent: typeof import('./src/components/LoadingContent.vue')['default']
    MessageContent: typeof import('./src/components/MessageContent.vue')['default']
    MixChartOne: typeof import('./src/components/echarts/mix/mixChartOne/index.vue')['default']
    MyUploader: typeof import('./src/components/myUploader/myUploader.vue')['default']
    OnceMore: typeof import('./src/components/onceMore/index.vue')['default']
    PieChartOne: typeof import('./src/components/echarts/pie/pieChartOne/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollList: typeof import('./src/components/scrollList.vue')['default']
  }
}
